# Generated by Django 3.2.16 on 2023-12-27 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20231224_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
